apiVersion: apps/v1
kind: Deployment
metadata:
  name: madu-app-cl9jwk-v1-0-0
  labels:
    app: madu-app-cl9jwk-v1-0-0
    applicationId: app_657e7039-ebb3-4514-a74b-d6a1dcd65fe5
    version: v1.0.0
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app: madu-app-cl9jwk-v1-0-0
  template:
    metadata:
      labels:
        app: madu-app-cl9jwk-v1-0-0
        applicationId: app_657e7039-ebb3-4514-a74b-d6a1dcd65fe5
        version: v1.0.0
        organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
        projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
