apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: test-app-zje58y-v1-0-0
    applicationId: app_e8b5f625-da7e-41a1-bdf5-1696d2e2dcf4
    version: v1.0.0
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    projectId: project_c51656d0-4d61-40eb-9d76-2681b7eb493e
    environmentId: env_8ccb9449-73fb-4193-987a-97071d9f60a6
  name: test-app-zje58y-v1-0-0
spec:
  selector:
    app: test-app-zje58y-v1-0-0
