apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: madu-app-vlzb8w-v1-0-0
  labels:
    app: madu-app-vlzb8w-v1-0-0
    applicationId: app_2c366b81-3976-484f-9641-a60696aa9d24
    version: v1.0.0
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    projectId: project_c51656d0-4d61-40eb-9d76-2681b7eb493e
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: madu-app-vlzb8w-v1-0-0
