apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts:
        - port: 80
          targetPort: 80
          protocol: TCP
          apiSpec:
            gitPath: madutesting
      healthChecks: []
      name: madu-app-vzxj64-main
      imagePullPolicy: Always
      imageRegistry: docker.io//madu-app-vzxj64
      imagePullSecretName: imagepull-docker
      credentialId: credential_06b9cd16-09a2-4286-b02a-3d9a08d5a746
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: madu-app-vzxj64
    version: v1.0.0
    applicationId: app_ad5196e6-daeb-4b5d-b01a-dcbaf6eb0c21
    projectId: project_c51656d0-4d61-40eb-9d76-2681b7eb493e
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    environmentId: env_cca49729-8f37-4aa4-981e-155a643363e6
    environmentName: staging
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: madu-app-vzxj64
  serviceType: ClusterIP
  version: v1.0.0
  namespace: qetesting2-staging
