apiVersion: apps/v1
kind: Deployment
metadata:
  name: madu-app-j6jx5y-v1-0-0
  labels:
    app: madu-app-j6jx5y-v1-0-0
    applicationId: app_6fbbf07c-f763-4e4d-bc85-80dd275064e8
    version: v1.0.0
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    projectId: project_c51656d0-4d61-40eb-9d76-2681b7eb493e
    environmentId: env_29b2c391-17bd-4346-8d22-e7f2ce42a2e7
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app: madu-app-j6jx5y-v1-0-0
  template:
    metadata:
      labels:
        app: madu-app-j6jx5y-v1-0-0
        applicationId: app_6fbbf07c-f763-4e4d-bc85-80dd275064e8
        version: v1.0.0
        organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
        projectId: project_c51656d0-4d61-40eb-9d76-2681b7eb493e
        environmentId: env_29b2c391-17bd-4346-8d22-e7f2ce42a2e7
