apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: madu-app-lp00a1-v1-0-0
    applicationId: app_e34c075d-385c-4bff-8261-7b8847a6b89b
    version: v1.0.0
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    projectId: project_c51656d0-4d61-40eb-9d76-2681b7eb493e
  name: madu-app-lp00a1-v1-0-0
spec:
  selector:
    app: madu-app-lp00a1-v1-0-0
