apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: madu-app-ck9pxp-v1-0-0
    applicationId: app_de6990ac-b1bd-410a-b2df-d8cce37482f4
    version: v1.0.0
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    projectId: project_c51656d0-4d61-40eb-9d76-2681b7eb493e
    environmentId: env_cca49729-8f37-4aa4-981e-155a643363e6
  name: madu-app-ck9pxp-v1-0-0
spec:
  selector:
    app: madu-app-ck9pxp-v1-0-0
