apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: test-app-bznan3-main
      imagePullPolicy: Always
      imageRegistry: docker.io//test-app-bznan3
      imagePullSecretName: imagepull-docker
      credentialId: credential_9eae8d21-9787-4ae3-9aad-91749a86549c
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 86400
  labels:
    app: test-app-bznan3
    version: v1.0.0
    applicationId: app_7ffffbfa-fe32-4276-94a7-0c247cada9d6
    projectId: project_c51656d0-4d61-40eb-9d76-2681b7eb493e
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    environmentId: env_8ccb9449-73fb-4193-987a-97071d9f60a6
    environmentName: test-env
  horizontalAutoScalingRules: []
  volumes: []
  type: CronJob
  name: test-app-bznan3
  cronTab: 0 0 1 * *
  version: v1.0.0
  namespace: test-ns
