apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: tag
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts:
        - port: 80
          targetPort: 80
          protocol: TCP
          apiSpec:
            gitPath: madutesting
      healthChecks: []
      name: madu-app-mvh1i7-main
      imagePullPolicy: Always
      imageRegistry: madutesting/image
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: madu-app-mvh1i7
    version: v1.0.0
    applicationId: app_bca006a0-7145-409f-89e9-80915f415d6f
    projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    environmentId: env_fcb8722b-9ada-4602-b7d0-a674301e65d0
    environmentName: staging
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: madu-app-mvh1i7
  serviceType: ClusterIP
  version: v1.0.0
  namespace: qetesting-staging
