apiVersion: v1
kind: ConfigMap
metadata:
  name: config-dev
  namespace: qetesting-dev
  labels:
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
    environmentId: env_9dbd4258-4fa9-4f5c-a695-a6dea3098aef
data:
  KEY: '123'
