apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: madu-app-9eelfy-v1-0-0
  labels:
    app: madu-app-9eelfy-v1-0-0
    applicationId: app_4cf059d4-80c7-407a-a0f5-23fe07ba61a8
    version: v1.0.0
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
    environmentId: env_9dbd4258-4fa9-4f5c-a695-a6dea3098aef
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: madu-app-9eelfy-v1-0-0
