apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts:
        - port: 80
          targetPort: 80
          protocol: TCP
          apiSpec:
            gitPath: madutesting
      healthChecks: []
      name: madu-app-3b8ti8-main
      imagePullPolicy: Always
      imageRegistry: docker.io//madu-app-3b8ti8
      imagePullSecretName: imagepull-docker
      credentialId: credential_00bb092a-13ca-4dd7-8f2b-13bab2dd5b52
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: madu-app-3b8ti8
    version: v1.0.0
    applicationId: app_8e65442e-0f97-4764-9c2e-8789e41bd12b
    projectId: project_c51656d0-4d61-40eb-9d76-2681b7eb493e
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    environmentId: env_29b2c391-17bd-4346-8d22-e7f2ce42a2e7
    environmentName: prod
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: madu-app-3b8ti8
  serviceType: ClusterIP
  version: v1.0.0
  namespace: qetesting2-prod
