apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts:
        - port: 80
          targetPort: 80
          protocol: TCP
          apiSpec:
            gitPath: madutesting
      healthChecks: []
      name: test-app-mbbp5q-main
      imagePullPolicy: Always
      imageRegistry: docker.io//test-app-mbbp5q
      imagePullSecretName: imagepull-docker
      credentialId: credential_ddfed9cd-6ec6-4eb9-bb98-8d7074194131
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: test-app-mbbp5q
    version: v1.0.0
    applicationId: app_1461c4f7-4c1b-47b0-b9b9-eb69fa8aca62
    projectId: project_c51656d0-4d61-40eb-9d76-2681b7eb493e
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    environmentId: env_29b2c391-17bd-4346-8d22-e7f2ce42a2e7
    environmentName: prod
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: test-app-mbbp5q
  serviceType: ClusterIP
  version: v1.0.0
  namespace: qetesting2-prod
