apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    reloader.stakater.com/auto: 'true'
  labels:
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
    applicationId: app_d7329b89-3a31-45ff-8602-37d65b72046f
    version: v1.0.0
    environmentId: env_c327b5e9-bf9f-465a-b67b-ebee74be369d
  name: madu-app-82iopd-v1-0-0
spec:
  successfulJobsHistoryLimit: 10
  jobTemplate:
    metadata:
      annotations: {}
      labels:
        organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
        projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
        applicationId: app_d7329b89-3a31-45ff-8602-37d65b72046f
        version: v1.0.0
        environmentId: env_c327b5e9-bf9f-465a-b67b-ebee74be369d
    spec:
      template:
        metadata:
          labels:
            organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
            projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
            applicationId: app_d7329b89-3a31-45ff-8602-37d65b72046f
            version: v1.0.0
            environmentId: env_c327b5e9-bf9f-465a-b67b-ebee74be369d
