apiVersion: configs.skyu.io/v1
kind: SkyUConfig
metadata:
  name: helm-app-v1-0-0-secret
  labels:
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
    applicationId: app_cab32d8c-80f5-448b-9699-11c7abadf609
spec:
  data:
    username: ${{secret::secret_ee70f532-6ae5-4c5a-b5db-7059fa2fe2f0:}}
    password: ${{secret::secret_e9daa7a2-afc1-4bcc-9ab3-e6571a9f693e:}}
  skyuControlPlaneAPI:
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
