apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts:
        - port: 80
          targetPort: 80
          protocol: TCP
          apiSpec:
            gitPath: madutesting
      healthChecks: []
      name: madu-app-pr9k04-main
      imagePullPolicy: Always
      imageRegistry: docker.io//madu-app-pr9k04
      imagePullSecretName: imagepull-docker
      credentialId: credential_72ece625-4c31-4bb1-aa8f-223689ee2078
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: madu-app-pr9k04
    version: v1.0.0
    applicationId: app_ae49796b-f096-4105-8e31-d724512e0faf
    projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    environmentId: env_c327b5e9-bf9f-465a-b67b-ebee74be369d
    environmentName: prod
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: madu-app-pr9k04
  serviceType: ClusterIP
  version: v1.0.0
  namespace: qetesting-prod
