apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: madu-app-0nu2tx-v1-0-0
  labels:
    app: madu-app-0nu2tx-v1-0-0
    applicationId: app_31319ae8-b0c7-45b4-aabd-16fb9c9c20e8
    version: v1.0.0
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: madu-app-0nu2tx-v1-0-0
