apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: madu-app-vqelhd-main
      imagePullPolicy: Always
      imageRegistry: docker.io//madu-app-vqelhd
      imagePullSecretName: imagepull-docker
      credentialId: credential_8d849cdd-cb33-4995-8666-4c916b43a9b0
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 86400
  labels:
    app: madu-app-vqelhd
    version: v1.0.0
    applicationId: app_97687429-a7cf-4b01-a2db-6074e3538298
    projectId: project_c51656d0-4d61-40eb-9d76-2681b7eb493e
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    environmentId: env_29b2c391-17bd-4346-8d22-e7f2ce42a2e7
    environmentName: prod
  horizontalAutoScalingRules: []
  volumes: []
  type: CronJob
  name: madu-app-vqelhd
  cronTab: 0 0 1 * *
  version: v1.0.0
  namespace: qetesting2-prod
