apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers: []
  name: helm
  type: HelmChart
  horizontalAutoScalingRules: []
  volumes: []
  version: v1.0.0
  labels:
    app: helm
    version: v1.0.0
    applicationId: app_66c14b50-9f19-4d85-80e2-14317bdf4f59
    projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    environmentId: env_c327b5e9-bf9f-465a-b67b-ebee74be369d
    environmentName: prod
  namespace: qetesting-prod
