apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers: []
  name: helm-app
  type: HelmChart
  horizontalAutoScalingRules: []
  volumes: []
  version: v1.0.0
  labels:
    app: helm-app
    version: v1.0.0
    applicationId: app_cab32d8c-80f5-448b-9699-11c7abadf609
    projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    environmentId: env_9dbd4258-4fa9-4f5c-a695-a6dea3098aef
    environmentName: dev
  namespace: qetesting-dev
