apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts:
        - port: 80
          targetPort: 80
          protocol: TCP
          apiSpec:
            gitPath: madutesting
      healthChecks: []
      name: madu-app-edpjeg-main
      imagePullPolicy: Always
      imageRegistry: docker.io//madu-app-edpjeg
      imagePullSecretName: imagepull-docker
      credentialId: credential_a164fb05-ff89-4bb5-a771-27bce828df90
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: madu-app-edpjeg
    version: v1.0.0
    applicationId: app_cc015ad2-6036-4ac4-ba29-3212333b48bb
    projectId: project_c51656d0-4d61-40eb-9d76-2681b7eb493e
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    environmentId: env_541b1768-d61f-4bb0-a53b-0fa628d393df
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: madu-app-edpjeg
  serviceType: ClusterIP
  version: v1.0.0
  namespace: qetesting2-dev
