apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: madu-app-82iopd-main
      imagePullPolicy: Always
      imageRegistry: docker.io//madu-app-82iopd
      imagePullSecretName: imagepull-docker
      credentialId: credential_96e2a77d-db88-4a58-a556-a45f46216134
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 86400
  labels:
    app: madu-app-82iopd
    version: v1.0.0
    applicationId: app_d7329b89-3a31-45ff-8602-37d65b72046f
    projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    environmentId: env_9dbd4258-4fa9-4f5c-a695-a6dea3098aef
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: CronJob
  name: madu-app-82iopd
  cronTab: 0 0 1 * *
  version: v1.0.0
  namespace: qetesting-dev
