apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts:
        - port: 80
          targetPort: 80
          protocol: TCP
          apiSpec:
            gitPath: madutesting
      healthChecks: []
      name: madu-app-xvjssa-main
      imagePullPolicy: Always
      imageRegistry: docker.io//madu-app-xvjssa
      imagePullSecretName: imagepull-docker
      credentialId: credential_146a87bc-5025-4a96-9783-ff3d2f83ab17
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: madu-app-xvjssa
    version: v1.0.0
    applicationId: app_0859683e-23dd-40e9-98d5-0aa9df462d49
    projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    environmentId: env_9dbd4258-4fa9-4f5c-a695-a6dea3098aef
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: madu-app-xvjssa
  serviceType: ClusterIP
  version: v1.0.0
  namespace: qetesting-dev
