apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
    orgId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    namespace: qetesting-dev
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
        orgId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
        namespace: qetesting-dev
        organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80