apiVersion: apps/v1
kind: Deployment
metadata:
  name: madu-test-v1-0-0
  labels:
    app: madu-test-v1-0-0
    applicationId: app_68e500ff-00ce-44c0-807c-97198f9c53b8
    version: v1.0.0
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
    environmentId: env_9dbd4258-4fa9-4f5c-a695-a6dea3098aef
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app: madu-test-v1-0-0
  template:
    metadata:
      labels:
        app: madu-test-v1-0-0
        applicationId: app_68e500ff-00ce-44c0-807c-97198f9c53b8
        version: v1.0.0
        organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
        projectId: project_b7c64762-48e8-4b3b-a0b8-3b97faeb217f
        environmentId: env_9dbd4258-4fa9-4f5c-a695-a6dea3098aef
