apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts:
        - port: 80
          targetPort: 80
          protocol: TCP
          apiSpec:
            gitPath: madutesting
      healthChecks: []
      name: madu-app-2aqj56-main
      imagePullPolicy: Always
      imageRegistry: docker.io//madu-app-2aqj56
      imagePullSecretName: imagepull-docker
      credentialId: credential_ada1a598-6fc7-4f6e-8d0e-e0f88cc09123
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: madu-app-2aqj56
    version: v1.0.0
    applicationId: app_671fc4c1-6ede-4bf8-a2b1-58a5fff80c48
    projectId: project_c51656d0-4d61-40eb-9d76-2681b7eb493e
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    environmentId: env_29b2c391-17bd-4346-8d22-e7f2ce42a2e7
    environmentName: prod
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: madu-app-2aqj56
  serviceType: ClusterIP
  version: v1.0.0
  namespace: qetesting2-prod
