apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: madu-app-2aqj56-v1-0-0
  labels:
    app: madu-app-2aqj56-v1-0-0
    applicationId: app_671fc4c1-6ede-4bf8-a2b1-58a5fff80c48
    version: v1.0.0
    organizationId: org_20c6c833-c6da-41ca-85b9-9573910c5b75
    projectId: project_c51656d0-4d61-40eb-9d76-2681b7eb493e
    environmentId: env_29b2c391-17bd-4346-8d22-e7f2ce42a2e7
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: madu-app-2aqj56-v1-0-0
